//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumbersToWordsConverter.NumberToWordService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberToWordService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConvertToWords", ReplyAction="http://tempuri.org/IService/ConvertToWordsResponse")]
        string ConvertToWords(double number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/ConvertToWords", ReplyAction="http://tempuri.org/IService/ConvertToWordsResponse")]
        System.Threading.Tasks.Task<string> ConvertToWordsAsync(double number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : NumbersToWordsConverter.NumberToWordService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<NumbersToWordsConverter.NumberToWordService.IService>, NumbersToWordsConverter.NumberToWordService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConvertToWords(double number) {
            return base.Channel.ConvertToWords(number);
        }
        
        public System.Threading.Tasks.Task<string> ConvertToWordsAsync(double number) {
            return base.Channel.ConvertToWordsAsync(number);
        }
    }
}
